#!/usr/bin/env ruby

# Defines the command line interface for the sensor framework
#
#  
require_relative 'lib/sensor'
require 'optparse'

include Sensor

unless ARGV[0]
  puts "Must provide a file name to act on."
  puts ""
  puts "Example Usage: ruby sensor foobar.csv"
  exit 1
end

if ARGV[0] =~ /\A-/ && ARGV[0] != '--help'
  puts "Must provide a filename as the first argument"
  puts ""
  puts "Example Usage: ruby sensor foobar.csv -m w"
  exit 1
end

options = { file: ARGV[0] }

OptionParser.new do |opts|
  opts.banner = "The following flags are available:"

  opts.on("-r", "--read", "Read from a given file") do |r|
    options[:read] = r
  end

  opts.on("-w", "--write", "Create and write to a file with the given filename") do |w|
    options[:write] = w
  end

  opts.on("-x", "--execute", "Execute a given file") do |e|
    options[:execute] = e
  end

  opts.on("-c", "--content CONTENT", "Accepts a string of file with contents for writing.
                                     Must be provided when passing the --write flag") do |c|
    options[:content] = c
  end
end.parse!

Sensor::Ingest.from_cli(options)
