#!/usr/bin/env ruby

# Defines the command line interface for the sensor framework

require_relative 'lib/sensor'
require 'optparse'

include Sensor

unless ARGV[0]
  puts "Must provide a filename to act on."
  puts ""
  puts "Example Usage: ruby sensor foobar.csv"
  exit 1
end

if ARGV[0] =~ /\A-/ && ARGV[0] != '--help'
  puts "Must provide a filename as the first argument"
  puts ""
  puts "Example Usage: ruby sensor foobar.csv -w -c 'this,is,fine'"
  exit 1
end

options = { filename: ARGV[0] }

OptionParser.new do |opts|
  opts.banner = "The following flags are available:"

  opts.on("-w", "--write", "Create and write to a file with the given filename") do |w|
    options[:write] = w
  end

  opts.on("-u", "--update", "Update a file with the given filename") do |u|
    options[:update] = u
  end

  opts.on("-d", "--delete", "Delete a file with the given filename") do |d|
    options[:delete] = d
  end

  opts.on("-x", "--execute", "Execute a given file") do |e|
    options[:execute] = e
  end

  opts.on("-c", "--content CONTENT", "Accepts a string with contents for writing.
                                     Must be provided when passing the --write or --update flag") do |c|
    options[:content] = c
  end
end.parse!

Sensor::Ingestor.read_from_cli(options)
